version: '3.9'

services:
  # Web service 1
  web1:
    image: dnais1210/edu-keepalive:v1
    networks:
      - webnet
    environment:
      - DATABASE_NAME=eduplateforme
      - DATABASE_USER=eduplateforme
      - DATABASE_PASSWORD=eduplateforme
      - DATABASE_HOST=192.168.56.10
      - DATABASE_PORT=3306
    volumes:
      - media_data:/app/media

  # Web service 2
  web2:
    image: dnais1210/edu-keepalive:v1
    networks:
      - webnet
    environment:
      - DATABASE_NAME=eduplateforme
      - DATABASE_USER=eduplateforme
      - DATABASE_PASSWORD=eduplateforme
      - DATABASE_HOST=192.168.56.10
      - DATABASE_PORT=3306
    volumes:
      - media_data:/app/media

  # Web service 3
  web3:
    image: dnais1210/edu-keepalive:v1
    networks:
      - webnet
    environment:
      - DATABASE_NAME=eduplateforme
      - DATABASE_USER=eduplateforme
      - DATABASE_PASSWORD=eduplateforme
      - DATABASE_HOST=192.168.56.10
      - DATABASE_PORT=3306
    volumes:
      - media_data:/app/media

  # HAProxy service for MASTER
  haproxy-master:
    build: ./haproxy
    networks:
      - webnet
    ports:
      - "80:80"  # HAProxy listens on port 80
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - web1
      - web2
      - web3
    environment:
      - KEEPALIVED_INTERFACE=eth0  # Interface for Keepalived

  # HAProxy service for BACKUP
  haproxy-backup:
    build: ./haproxy
    networks:
      - webnet
    ports:
      - "8080:80"  # HAProxy listens on port 8080, backup mode
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - web1
      - web2
      - web3
    environment:
      - KEEPALIVED_INTERFACE=eth0  # Interface for Keepalived

  # Keepalived service for MASTER (VIP holder)
  keepalived-master:
    image: osixia/keepalived:latest
    networks:
      - webnet
    environment:
      - KEEPALIVED_INTERFACE=eth0  # Interface réseau Docker
      - KEEPALIVED_VIRTUAL_IPS=192.168.56.100  # IP virtuelle
      - KEEPALIVED_UNICAST_PEERS=keepalived-backup  # Lien avec le conteneur BACKUP
      - KEEPALIVED_VRRP_INSTANCE=VI_1
      - KEEPALIVED_PRIORITY=101  # Priorité plus élevée pour MASTER
    volumes:
      - ./keepalived/master.conf:/etc/keepalived/keepalived.conf  # Monter le fichier de config
    depends_on:
      - haproxy-master  # Assurez-vous que HAProxy MASTER est lancé avant Keepalived

  # Keepalived service for BACKUP (Failover in case MASTER fails)
  keepalived-backup:
    image: osixia/keepalived:latest
    networks:
      - webnet
    environment:
      - KEEPALIVED_INTERFACE=eth0
      - KEEPALIVED_VIRTUAL_IPS=192.168.56.100  # L'IP virtuelle partagée avec le MASTER
      - KEEPALIVED_UNICAST_PEERS=keepalived-master  # Lien avec le conteneur MASTER
      - KEEPALIVED_VRRP_INSTANCE=VI_1
      - KEEPALIVED_PRIORITY=100  # Priorité inférieure pour BACKUP
    volumes:
      - ./keepalived/backup.conf:/etc/keepalived/keepalived.conf  # Monter le fichier de config
    depends_on:
      - haproxy-backup  # Assurez-vous que HAProxy BACKUP est lancé avant Keepalived

networks:
  webnet:
    driver: bridge  # Réseau interne Docker

volumes:
  media_data:
