pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'dnais1210/edu-plateform'
        DOCKER_CREDENTIALS = 'docker-credential'
        // KUBECONFIG = '/var/kubeconfig' // Chemin vers ton fichier kubeconfig
    }

    stages {
        stage('Cloner le code') {
            steps {
                git branch: 'main', url: 'https://github.com/ibrahimbakayoko/edu-keepalive.git'
            }
        }

        stage('Construire l’image Docker') {
            steps {
                script {
                    sh 'docker build -t $DOCKER_IMAGE:$BUILD_NUMBER -f eduplateforme/Dockerfile .'
                }
            }
        }

        stage('Pousser sur Docker Hub') {
            steps {
                script {
                    withDockerRegistry([credentialsId: "$DOCKER_CREDENTIALS", url: ""]) {
                        sh 'docker push $DOCKER_IMAGE:$BUILD_NUMBER'
                    }
                }
            }
        }

//         stage('Déployer sur Kubernetes') {
//             steps {
//                 script {
//                      // sh  'kubectl get nodes'
//                    // sh 'kubectl apply -f k8s/deployment.yaml'
//                    //  sh 'kubectl apply -f k8s/service.yaml'
//                 }
//             }
//        }
    }
}
